### ISSUE TITLE
Issue upgrading from 4.1.1 -> 4.1.2 or greater

### ISSUE THREAD

**Issue by sethmoore** [splitio/.net-client#136] opened 2019-06-17 17:30 UTC
It looks like upgrading beyond 4.1.1 is pulling in a dependency that we can't currently resolve:
`Unable to resolve dependencies. 'System.IdentityModel.Tokens.Jwt 4.0.4.403061554' is not compatible with 'Microsoft.IdentityModel.Protocols 2.1.5 constraint: System.IdentityModel.Tokens.Jwt (>= 5.1.5)'.` due to other dependencies in our code and our version of .Net.

**Comment by patricioe** [comment] 2019-06-17 18:22
Hi Seth,

Thanks for bringing this to our attention.  We'll get back to you as soon as we can and our apologies for the inconvenience.

**Comment by NicoZelaya** [comment] 2019-06-19 17:39
Hi @sethmoore ! Hope you're having a great day.

We took a look on our side and we can't find that dependency in our tree. We don't use anything related with IdentityModel directly and it doesn't seem to be a dependency of our dependencies either. 

Could you double check to see if that dependency is coming from somewhere else? An option besides Nuget  would be a tool similar to this one which outputs the entire tree: https://www.npmjs.com/package/nuget-tree (in this case you need to have npm, which comes along with Node)

In any case, the idea would be to get some sense on which library is adding that dependency. 
If you get a tree or anything else but don't feel comfortable sharing it here, please send an email to support@split.io also linking to this issue and we'll continue the conversation there.

Another thing we would like to confirm is the version of .Net Framework you're using, is it 4.5.1 ?

Regards,
Nico.

**Comment by patricioe** [comment] 2019-06-24 18:27
Hi @sethmoore 

Repinging here. Mind setting us know if you or your team spent any more time on this? Our team was not able to find this dependency. Not even when installing this SDK version on a new and simple app. 

Let us know.

**Comment by sethmoore** [comment] 2019-06-25 14:13
So when I posted this issue we were on 4.5.1, but we have since upgraded to 4.7 and I just tried upgrading again with the same result.  I'm trying to update all of the dependencies from here but as you can imagine this is turning into quite the rabbit hole and it's starting to require refactoring efforts.  I'll try to open up another branch and create that dependency tree for you.

**Comment by sethmoore** [comment] 2019-06-25 14:40
This is a partial of the tree before the upgrade:
`├─┬ Microsoft.IdentityModel.JsonWebTokens 5.4.0
│ ├─┬ Microsoft.IdentityModel.Tokens 5.4.0
│ │ ├── Microsoft.IdentityModel.Logging 5.4.0
│ │ └── Newtonsoft.Json 10.0.1
│ └── Newtonsoft.Json 10.0.1
├─┬ Auth0.OpenIdConnectSigningKeyResolver 1.0.0
│ └── Microsoft.IdentityModel.Protocol.Extensions 1.0.4.403061554
└─┬ Microsoft.IdentityModel.Protocols.OpenIdConnect 2.1.5
  └── Microsoft.IdentityModel.Protocols 2.1.5`

Then when I try to upgrade this is the message I get:
`Attempting to gather dependency information for package 'Splitio.4.1.3' with respect to project 'Presentation\Nop.Web.Framework', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 1.63 min
Attempting to resolve dependencies for package 'Splitio.4.1.3' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'System.Net.Http 4.3.1 constraint: System.Security.Cryptography.X509Certificates (>= 4.3.0)', 'Microsoft.IdentityModel.Protocols 2.1.5 constraint: System.IdentityModel.Tokens.Jwt (>= 5.1.5)'
Unable to resolve dependencies. 'System.IdentityModel.Tokens.Jwt 4.0.4.403061554' is not compatible with 'Microsoft.IdentityModel.Protocols 2.1.5 constraint: System.IdentityModel.Tokens.Jwt (>= 5.1.5)'.
Time Elapsed: 00:01:37.6630157
========== Finished ==========`

**Comment by NicoZelaya** [comment] 2019-06-27 21:14
Hi @sethmoore,

we tried a bunch of different configurations on our end using .Net Framework 4.7.2, starting from a lower version of the SDK and moving the versions up, doing the opposite and going down but we were not able to reproduce that issue for now.
We created different application types where we installed the dependencies you shared with us and the Split SDK. 

This is the dependency tree we get when we upgrade to Splitio.4.1.3 (same version we see on your previous message):
<img width="596" alt="Screen Shot 2019-06-27 at 17 55 18" src="https://user-images.githubusercontent.com/5522668/60300204-dbea6000-9904-11e9-9195-1efc7b18e589.png">

We would like to ask for more context on your setup. 
- Do you have any other dependencies installed? If so, could you share it with us so we can try to replicate under the same conditions? A packages.config file or whatever is easiest for you.
- At the same time, if you have any other details you think might be relevant here, please share it as well so we can keep trying to reproduce and find the root cause of the problem.
- Also, could you briefly walk us through how it is that you're trying to upgrade Splitio package? Are you trying to update many dependencies? e.g: do you search for Splitio package and try to upgrade just that one? 

It will probably be better if you reach out through support@split.io where your information will not be open to the public and we can provide better tracking of the problem you're experiencing. Just mention this issue or put the link somewhere, our support team is already aware of this.

Our sincere apologies for the inconveniences you experienced so far.

Best regards,
Nico.

**Comment by sethmoore** [comment] 2019-07-05 14:15
So I just manually incremented the version in the csproj files (not using the nuget "upgrade") and everything is building fine.  I'm going to run a few more tests but it seems like nuget was greedily updating dependencies perhaps?

**Comment by sethmoore** [comment] 2019-07-05 15:23
So now I'm on `4.1.3` in the csproj file and according to nuget, but for some reason I can't pass attributes into the SDK.  I'm getting a `No overloaded method for 'Track' takes 5 arguments`.  I tried deleting and restoring all of my nuget packages but still getting the same error.  This is what my csproj file looks like `<package id="Splitio" version="4.1.3" targetFramework="net472" />`.

**Comment by NicoZelaya** [comment] 2019-07-05 19:06
Hey @sethmoore, 

for the first one, the only thing I can say for now is "maybe". We had no luck trying to reproduce that conflict, so it might had been related to some sort of greedy update.

For the other issue with Track method, can you share how are you invoking it? Which params are you using? Of which type? 
This is the signature of that function as of version `4.1.3` (before that version the optional param "properties" was not part of it:
` bool Track(string key, string trafficType, string eventType, double? value = null, Dictionary<string, object> properties = null);`

Any other information you think might help us reproduce would be appreciated. Again, if you think it would be better for you, you can reach out through support@split.io. 

Best,
Nico.

**Comment by sethmoore** [comment] 2019-07-08 20:49
@NicoZelaya Looks like I missed updating the version in the csproj.  once I also did that the manual upgrade works.

**Comment by NicoZelaya** [comment] 2019-07-09 12:58
Thank you for the update @sethmoore! 

I'll proceed and close the issue then, but feel free to re-open or create a new one if you are still experiencing any inconvenience.

Have a wonderful rest of your week!
Nico.

**Closed by NicoZelaya** 2019-07-09 12:58 UTC
